// Code generated by Slice Machine. DO NOT EDIT.

import NewCustomSlice from './NewCustomSlice/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	new_custom_slice: NewCustomSlice,
	rich_text: RichText
};
