// Code generated by Slice Machine. DO NOT EDIT.

import CusotomCoponent from './CusotomCoponent/index.svelte';
import NewCustomSlice from './NewCustomSlice/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	cusotom_coponent: CusotomCoponent,
	new_custom_slice: NewCustomSlice,
	rich_text: RichText
};
